### ISSUE TITLE
Failed to create a containerizer: Could not create DockerContainerizer: Failed to execute 'docker version': exited with status 1

### ISSUE THREAD

**Issue by dontrebootme** [redjack/docker-mesos#11]
Getting the following when trying to launch the container:
```
I0218 00:57:06.777551     1 main.cpp:142] Build: 2014-11-22 05:29:57 by root
I0218 00:57:06.778921     1 main.cpp:144] Version: 0.21.0
I0218 00:57:06.778933     1 main.cpp:147] Git tag: 0.21.0
I0218 00:57:06.778936     1 main.cpp:151] Git SHA: ab8fa655d34e8e15a4290422df38a18db1c09b5b
Failed to create a containerizer: Could not create DockerContainerizer: Failed to execute 'docker version': exited with status 1
```

I have the following in fig:
```
slave1:
  image: redjack/mesos-slave:0.21.0
  ports:
    - "5051:5051"
  links:
    - "zk1:zookeeper1"
  environment:
    MESOS_PORT: "5051"
    MESOS_MASTER: zk:zookeeper1:2181/mesos
    MESOS_HOSTNAME: mesos-slave1
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_ISOLATOR: "cgroups/cpu,cgroups/mem"
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: "5mins"
  volumes:
    - /run/docker.sock:/run/docker.sock
    - /sys:/sys
    - /proc:/proc
```

**Comment by dontrebootme** [comment]
From within the container:
```
root@b15e5c3015b6:/var/log# cat docker.io.log
2015/02/18 02:06:19 docker daemon: 1.0.1 990021a; execdriver: native; graphdriver:
[6488aea8] +job serveapi(unix:///var/run/docker.sock)
[6488aea8] +job initserver()
[6488aea8.initserver()] Creating server
2015/02/18 02:06:19 Listening for HTTP on unix (/var/run/docker.sock)
[6488aea8] +job init_networkdriver()
[6488aea8.init_networkdriver()] creating new bridge for docker0
operation not permitted
[6488aea8] -job init_networkdriver() = ERR (1)
operation not permitted
[6488aea8] -job initserver() = ERR (1)
2015/02/18 02:06:19 operation not permitted
root@b15e5c3015b6:/var/log# docker version
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
2015/02/18 02:07:21 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

**Comment by paulcfx** [comment]
Hi @dontrebootme did you find a work around? I'm having the same issue running from within boot2docker.

**Comment by yangtao309** [comment]
@paulcfx 
in my centos 7, happend this error. where is problem? 

```
[root@kubernetes cd_demo]# docker logs a01cf532d5bf
I0321 08:17:19.334563     1 logging.cpp:172] INFO level logging started!
I0321 08:17:19.335260     1 main.cpp:142] Build: 2014-11-22 05:29:57 by root
I0321 08:17:19.335286     1 main.cpp:144] Version: 0.21.0
I0321 08:17:19.335300     1 main.cpp:147] Git tag: 0.21.0
I0321 08:17:19.335312     1 main.cpp:151] Git SHA: ab8fa655d34e8e15a4290422df38a18db1c09b5b
Failed to create a containerizer: Could not create DockerContainerizer: Failed to execute 'docker version': exited with status 127
```

uname -s & docker info 
```
[root@kubernetes cd_demo]# uname -a
Linux kubernetes 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@kubernetes cd_demo]# docker info
Containers: 7
Images: 140
Storage Driver: devicemapper
 Pool Name: docker-253:1-71668609-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 6.854 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 8.573 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
``

**Comment by tnachen** [comment]
what happens when you run docker version? and how are you starting the slave?

**Comment by yangtao309** [comment]
@tnachen 

```
# Zookeeper: -p 2181:2181 -p 2888:2888 -p 3888:3888
zookeeper:
  image: docker.yunat.com/jplock/zookeeper:3.4.5
  ports:
    - "2181"

master:
  image: docker.yunat.com/redjack/mesos-master:0.21.0
  hostname: master
  links:
    - zookeeper:zookeeper
  environment:
    - MESOS_ZK=zk://zookeeper:2181/mesos
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOG_DIR=/var/log
  ports:
    - "5050:5050"

marathon:
  image: docker.yunat.com/mesosphere/marathon
  links:
    - zookeeper:zookeeper
  ports:
    - "8090:8080"
  # this image does not respect MARATHON_ env variables, so adding the params via command
  command: --master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon

slave:
  image: redjack/mesos-slave:0.21.0
  links:
    - zookeeper:zookeeper
    - master:master
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/run/docker.sock:/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /sys:/sys:ro
    - mesosslace-stuff:/var/log
  expose:
    - "5051"

jenkins:
  image: jenkins
  links:
    - marathon:marathon
  volumes:
    - jenkins-stuff:/var/jenkins_home
    - .:/var/jenkins_data
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  ports:
    - "8081:8080"
```

in command terminal i will execute: fig up -d

docker --verision
```
~
[root@kubernetes cd_demo]# docker --version
Docker version 1.3.2, build 39fa2fa/1.3.2
```
